package site.chatgpt.seelenbinder.launchliftpracticeapp.android;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

@CapacitorPlugin(name = "PushRuntime")
public class PushRuntimePlugin extends Plugin {
    @PluginMethod
    public void getRuntimeStatus(PluginCall call) {
        // google_app_id is generated by the Google Services Gradle plug-in from
        // the controlled config. Its absence is detectable without linking
        // Firebase classes into an otherwise config-free debug build.
        int appIdResource = getContext().getResources().getIdentifier(
            "google_app_id",
            "string",
            getContext().getPackageName()
        );
        boolean firebaseConfigured = appIdResource != 0
            && !getContext().getString(appIdResource).trim().isEmpty();

        JSObject result = new JSObject();
        result.put("firebaseConfigured", firebaseConfigured);
        call.resolve(result);
    }
}
